# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# DATABASE - Render PostgreSQL
# ===============================
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/lost_found_db}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# JWT
# ===============================
app.jwt.secret=${JWT_SECRET:LostFound@SecureKey#2026VeryStrong123456789}
app.jwt.expiration=86400000

# ===============================
# CORS
# ===============================
app.cors.allowed-origins=${CORS_ORIGIN:*}

# ===============================
# FILE + MULTIPART
# ===============================
app.upload.dir=/tmp/uploads/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===============================
# LOGGING
# ===============================
logging.level.root=WARN
logging.level.com.lostfound=INFO
